version: "3.0"
services:
  wordpress:
    image: wordpress:5.7.2-apache
    restart: unless-stopped
    ports:
      - "8080:80"
    environment: 
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${USER_PASSWORD?Es necesario definir USER_PASSWORD}
    volumes:
      - wordpress:/var/www/html
  mariadb: 
    image: mariadb:10.6.3-focal
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD?Es necesario definir ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${USER_NAME:-wordpress}
      MYSQL_PASSWORD: ${USER_PASSWORD?Es necesario definir USER_PASSWORD}
  phpmyadmin:
    image: phpmyadmin:5.1.1-apache
    restart: unless-stopped
    ports:
      - 5432:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOSTS=mariadb
      - PMA_USER=wordpress
      - PMA_PASSWORD=${USER_PASSWORD?Es necesario definir USER_PASSWORD}

volumes:
  mariadb: 
  wordpress:
